export const GET_QUESTIONS_SUCCESS = 'GET-QUESTIONS-SUCCESS';
export const GET_QUESTIONS_FAILED = 'GET-QUESTIONS-FAILED';

export const GET_QUESTION_BY_ID_SUCCESS = 'GET-QUESTION-BY-ID-SUCCESS';
export const GET_QUESTION_BY_ID_FAILED = 'GET-QUESTION-BY-ID-FAILED';

export const ADD_QUESTION_SUCCESS = 'ADD-QUESTION-SUCCESS';
export const ADD_QUESTION_FAILED = 'ADD-QUESTION-FAILED';

export const UPDATE_QUESTION_SUCCESS = 'UPDATE-QUESTION-SUCCESS';
export const UPDATE_QUESTION_FAILED = 'UPDATE-QUESTION-FAILED';

export const REMOVE_QUESTION_SUCCESS = 'REMOVE-QUESTION-SUCCESS';
export const REMOVE_QUESTION_FAILED = 'REMOVE-QUESTION-FAILED';


export const LOGIN_SUCCESS = "LOGIN-SUCCESS";
export const LOGIN_FAILED = "LOGIN-FAILED";

export const LOGOUT = 'LOGOUT';

export const RESET_STATE = 'RESET-STATE';
export const TOGGLE_MODAL = 'TOGGLE-MODAL';
export const HANDLE_ANSWER = 'HANDLE-ANSWER';
export const GET_RESULT = 'GET-RESULT';
export const NEXT_QUESTION = 'NEXT-QUESTION';

export const TOKEN_TRUE = 'TOKEN-TRUE';